name: Nurx private NPM package build & publish
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Workspace
        id: setup_workspace
        uses: actions/checkout@v2

      # FUTURE -- lint commit message (shared action)

      # FUTURE -- lint package.json (shared action)

      - name: Install Node
        id: install_node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nurx'

      # https://github.com/actions/cache/blob/main/examples.md#node---npm
      - name: Reuse NPM Cache
        id: reuse_npm_cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-node12-{{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-node12-

      - name: Install Dependencies
        id: install_dependencies
        run: npm install --ignore-scripts

      - name: Lint Code
        id: run_lint
        run: npm run lint

      - name: Run Tests (with Coverage)
        id: run_tests
        run: npm run cover

      - name: Build the Package
        id: run_build
        run: npm run build --if-present

      # FUTURE? -- archive artifacts?

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    steps:
      - name: Setup Workspace
        id: setup_workspace
        uses: actions/checkout@v2

      - name: Install Node
        id: install_node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nurx'

      # https://github.com/actions/cache/blob/main/examples.md#node---npm
      - name: Reuse NPM Cache
        id: reuse_npm_cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-node12-{{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-node12-

      - name: Install Dependencies
        id: install_dependencies
        run: npm ci --ignore-scripts

      - name: Build the Package
        id: run_build
        run: npm run build --if-present

      - name: Publish
        id: publish
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

